// <auto-generated />
namespace AnyChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterTableRoomsAddRoomGuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterTableRoomsAddRoomGuid));
        
        string IMigrationMetadata.Id
        {
            get { return "201805060818303_AlterTableRoomsAddRoomGuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
